// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockWebApp.DataAccess;

namespace StockWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockWebApp.Models.EF_Models+Company", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("date");

                    b.Property<string>("iexId");

                    b.Property<bool>("isEnabled");

                    b.Property<string>("name");

                    b.Property<string>("type");

                    b.HasKey("symbol");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("StockWebApp.Models.EF_Models+CompanyList", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("avgTotalVolume");

                    b.Property<string>("calculationPrice");

                    b.Property<float>("change");

                    b.Property<float>("changePercent");

                    b.Property<float>("close");

                    b.Property<long>("closeTime");

                    b.Property<string>("companyName");

                    b.Property<float>("delayedPrice");

                    b.Property<long>("delayedPriceTime");

                    b.Property<float>("extendedChange");

                    b.Property<float>("extendedChangePercent");

                    b.Property<float>("extendedPrice");

                    b.Property<long>("extendedPriceTime");

                    b.Property<float>("high");

                    b.Property<float>("iexAskPrice");

                    b.Property<int>("iexAskSize");

                    b.Property<float>("iexBidPrice");

                    b.Property<int>("iexBidSize");

                    b.Property<int>("iexLastUpdated");

                    b.Property<float>("iexMarketPercent");

                    b.Property<float>("iexRealtimePrice");

                    b.Property<int>("iexRealtimeSize");

                    b.Property<int>("iexVolume");

                    b.Property<float>("latestPrice");

                    b.Property<string>("latestSource");

                    b.Property<string>("latestTime");

                    b.Property<long>("latestUpdate");

                    b.Property<int>("latestVolume");

                    b.Property<float>("low");

                    b.Property<long>("marketCap");

                    b.Property<float>("open");

                    b.Property<long>("openTime");

                    b.Property<float>("peRatio");

                    b.Property<float>("previousClose");

                    b.Property<string>("primaryExchange");

                    b.Property<string>("sector");

                    b.Property<float>("week52High");

                    b.Property<float>("week52Low");

                    b.Property<float>("ytdChange");

                    b.HasKey("symbol");

                    b.ToTable("Gainers");
                });

            modelBuilder.Entity("StockWebApp.Models.EF_Models+NewsData", b =>
                {
                    b.Property<string>("headline")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("datetime");

                    b.Property<string>("image");

                    b.Property<string>("related");

                    b.Property<string>("source");

                    b.Property<string>("summary");

                    b.Property<string>("url");

                    b.HasKey("headline");

                    b.ToTable("News");
                });
#pragma warning restore 612, 618
        }
    }
}
